package org.example.domain.enums;

public enum Equipamentos {

    CADEIRA_DE_RODAS, MULETA, ANDADOR, ORTESE, PROTESE, APARELHO_AUDITIVO, CADEIRA_HIGIENICA

    //CADEIRA_DE_RODAS, MULETA, ANDADOR, ÓRTESE, PRÓTESE -> ORTOPEDISTA
    //CADEIRA_HIGIÊNICA -> UROLOGISTA
    //APARELHO_AUDITIVO -> Otorrinolaringologista
}
